ARG RUBY_VERSION

FROM ruby:${RUBY_VERSION}-slim
RUN apt-get update -qq && apt-get install -y  build-essential libpq-dev nodejs imagemagick

ARG USER=myuser
RUN adduser  --disabled-login --gecos '' ${USER}
USER ${USER}

WORKDIR /home/${USER}/app

